// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IDigitalEscrow$Type } from "./IDigitalEscrow";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IDigitalEscrow"]: IDigitalEscrow$Type;
    ["contracts/escrow/IDigitalEscrow.sol:IDigitalEscrow"]: IDigitalEscrow$Type;
  }

  interface ContractTypesMap {
    ["IDigitalEscrow"]: GetContractReturnType<IDigitalEscrow$Type["abi"]>;
    ["contracts/escrow/IDigitalEscrow.sol:IDigitalEscrow"]: GetContractReturnType<IDigitalEscrow$Type["abi"]>;
  }
}
