// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { UUPSProxy$Type } from "./UUPSProxy";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["UUPSProxy"]: UUPSProxy$Type;
    ["contracts/proxy/UUPSProxy.sol:UUPSProxy"]: UUPSProxy$Type;
  }

  interface ContractTypesMap {
    ["UUPSProxy"]: GetContractReturnType<UUPSProxy$Type["abi"]>;
    ["contracts/proxy/UUPSProxy.sol:UUPSProxy"]: GetContractReturnType<UUPSProxy$Type["abi"]>;
  }
}
