// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BaseEscrow$Type } from "./BaseEscrow";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BaseEscrow"]: BaseEscrow$Type;
    ["contracts/escrow/BaseEscrow.sol:BaseEscrow"]: BaseEscrow$Type;
  }

  interface ContractTypesMap {
    ["BaseEscrow"]: GetContractReturnType<BaseEscrow$Type["abi"]>;
    ["contracts/escrow/BaseEscrow.sol:BaseEscrow"]: GetContractReturnType<BaseEscrow$Type["abi"]>;
  }
}
