// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DigitalEscrow$Type } from "./DigitalEscrow";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DigitalEscrow"]: DigitalEscrow$Type;
    ["contracts/escrow/DigitalEscrow.sol:DigitalEscrow"]: DigitalEscrow$Type;
  }

  interface ContractTypesMap {
    ["DigitalEscrow"]: GetContractReturnType<DigitalEscrow$Type["abi"]>;
    ["contracts/escrow/DigitalEscrow.sol:DigitalEscrow"]: GetContractReturnType<DigitalEscrow$Type["abi"]>;
  }
}
