// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { EscrowLib$Type } from "./EscrowLib";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EscrowLib"]: EscrowLib$Type;
    ["contracts/escrow/EscrowLib.sol:EscrowLib"]: EscrowLib$Type;
  }

  interface ContractTypesMap {
    ["EscrowLib"]: GetContractReturnType<EscrowLib$Type["abi"]>;
    ["contracts/escrow/EscrowLib.sol:EscrowLib"]: GetContractReturnType<EscrowLib$Type["abi"]>;
  }
}
