// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface EscrowLib$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "EscrowLib",
  "sourceName": "contracts/escrow/EscrowLib.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "addr",
          "type": "address"
        }
      ],
      "name": "InvalidAddress",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "InvalidAmount",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "length",
          "type": "uint256"
        }
      ],
      "name": "StringTooLong",
      "type": "error"
    }
  ],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220c125625357bd1c87fb2ac339a18181a57cbab7deaa90067f42fb907ad58d2fb764736f6c634300081c0033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220c125625357bd1c87fb2ac339a18181a57cbab7deaa90067f42fb907ad58d2fb764736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "EscrowLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<EscrowLib$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/escrow/EscrowLib.sol:EscrowLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<EscrowLib$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "EscrowLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<EscrowLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/escrow/EscrowLib.sol:EscrowLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<EscrowLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "EscrowLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<EscrowLib$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/escrow/EscrowLib.sol:EscrowLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<EscrowLib$Type["abi"]>>;
}
